import { StyleSheet } from "react-native";
import type { ThemeColors } from "@/src/context/ThemeContext";

export function createTasksStyles(colors: ThemeColors) {
  return StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    centered: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 32,
    },
    headerRow: {
      alignItems: "center",
      paddingHorizontal: 24,
      paddingTop: 12,
      paddingBottom: 12,
    },
    title: {
      fontSize: 23,
      fontWeight: "700",
      color: colors.textPrimary,
      marginLeft: -2,
      letterSpacing: -1.0,
    },
    subtitle: {
      alignSelf: "flex-start",
      fontSize: 15,
      color: colors.textSecondary,
      marginTop: 14,
    },
    sectionHeader: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 8,
      marginTop: 16,
    },
    list: {
      paddingHorizontal: 24,
      paddingBottom: 90,
    },
    centeredColumn: {
      alignItems: "center",
      justifyContent: "center",
      paddingBottom: 60,
    },
    loginContent: {
      alignItems: "center",
      paddingHorizontal: 32,
    },
    loginIcon: {
      width: 70,
      height: 70,
      tintColor: colors.accent,
      marginBottom: 16,
    },
    loginTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.textPrimary,
      textAlign: "center",
      marginBottom: 6,
    },
    loginSubtitle: {
      fontSize: 15,
      color: colors.textMuted,
      textAlign: "center",
      lineHeight: 20,
      marginBottom: 20,
    },
    loginButtonHovered: {
      backgroundColor: colors.accent,
      opacity: 0.92,
      transform: [{ scale: 1.015 }],
    },
    loginButton: {
      marginTop: 16,
      backgroundColor: colors.accent,
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 48,
      alignItems: "center",
    },
    loginButtonPressed: {
      opacity: 0.8,
    },
    loginButtonText: {
      fontSize: 15,
      fontWeight: "600",
      color: "#fff",
    },
    areaList: {
      maxHeight: 150,
      backgroundColor: colors.background,
      borderRadius: 12,
      marginTop: 4,
    },
    areaItem: {
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.divider,
    },
    areaItemText: {
      fontSize: 15,
      color: colors.textPrimary,
    },
    areaSelectedText: {
      fontSize: 15,
      color: colors.textPrimary,
    },
    areaPlaceholderText: {
      fontSize: 15,
      color: colors.textMuted,
    },
    createButton: {
      marginTop: 24,
      backgroundColor: colors.accent,
      borderRadius: 12,
      paddingVertical: 16,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    createButtonDisabled: {
      opacity: 0.35,
    },
    createButtonText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#fff",
    },
    fab: {
      position: "absolute",
      bottom: 24,
      right: 24,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 6,
    },
    fabPressed: {
      opacity: 0.85,
    },
    fabText: {
      fontSize: 28,
      fontWeight: "400",
      color: "#fff",
      marginTop: -2,
    },
    categoryGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 4,
    },
    categoryChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: colors.card,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    categoryChipActive: {
      backgroundColor: colors.accentMuted,
      borderColor: colors.accent,
    },
    categoryEmoji: {
      fontSize: 16,
    },
    categoryChipText: {
      fontSize: 13,
      fontWeight: "500",
      color: colors.textSecondary,
    },
    categoryChipTextActive: {
      color: colors.accent,
      fontWeight: "600",
    },
    segmentRow: {
      flexDirection: "row",
      marginHorizontal: 24,
      marginTop: 12,
      marginBottom: 4,
      backgroundColor: colors.card,
      borderRadius: 25,
      padding: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    segmentButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 10,
      borderRadius: 22,
      gap: 6,
    },
    segmentButtonActive: {
      backgroundColor: colors.accentMuted,
    },
    segmentText: {
      fontSize: 14,
      fontWeight: "500",
      color: colors.textMuted,
    },
    segmentTextActive: {
      color: colors.accent,
      fontWeight: "600",
    },
    segmentBadge: {
      backgroundColor: colors.border,
      borderRadius: 10,
      paddingHorizontal: 7,
      paddingVertical: 1,
      minWidth: 20,
      alignItems: "center",
    },
    segmentBadgeActive: {
      backgroundColor: colors.accent,
    },
    segmentBadgeText: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.textMuted,
    },
    segmentBadgeTextActive: {
      color: "#fff",
    },
    offerCard: {
      backgroundColor: colors.card,
      borderRadius: 14,
      padding: 18,
      marginBottom: 14,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    offerCardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 6,
    },
    offerTaskTitle: {
      fontSize: 17,
      fontWeight: "600",
      color: colors.textPrimary,
      flex: 1,
      marginRight: 12,
    },
    offerCardMeta: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 4,
    },
    offerTaskMeta: {
      fontSize: 13,
      color: colors.textMuted,
    },
    offerStatusBadge: {
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    offerStatusText: {
      fontSize: 12,
      fontWeight: "600",
    },
    offerPrice: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.accent,
    },
    offerCardFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 6,
    },
    offerDate: {
      fontSize: 12,
      color: colors.textMuted,
    },
    offerDetailLink: {
      fontSize: 13,
      fontWeight: "500",
      color: colors.accent,
    },
    offerCancelButton: {
      marginTop: 12,
      borderWidth: 1,
      borderColor: colors.danger,
      borderRadius: 10,
      paddingVertical: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    offerCancelButtonText: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.danger,
    },
    imageThumb: {
      width: 80,
      height: 80,
      borderRadius: 12,
    },
    imageRemove: {
      position: "absolute",
      top: 4,
      right: 4,
      backgroundColor: "rgba(0,0,0,0.6)",
      borderRadius: 12,
      width: 24,
      height: 24,
      alignItems: "center",
      justifyContent: "center",
    },
    imageRemoveText: {
      color: "#fff",
      fontSize: 13,
      fontWeight: "600",
    },
    imageAdd: {
      width: 80,
      height: 80,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
      borderStyle: "dashed",
      alignItems: "center",
      justifyContent: "center",
      gap: 2,
    },
    imageAddText: {
      fontSize: 24,
      color: colors.textMuted,
    },
    imageAddLabel: {
      fontSize: 10,
      color: colors.textMuted,
    },
  });
}
